### ISSUE TITLE
keychain returns nil

### ISSUE THREAD

**Issue by rashidasgari** [kishikawakatsumi/UICKeyChainStore#106]
Hi, I got this weird problem, When i wanna retrieve from keychain it works fine, but just after that when i wanna do it again in another class i get nil. 

this is how i call it:     
keyChain = [UICKeyChainStore keyChainStoreWithService:@"myapp.Login"];

**Comment by kishikawakatsumi** [comment]
It seems too strange. Could you please share reproducible project for further investigation?

**Comment by rashidasgari** [comment]
@kishikawakatsumi Since the project is for a client of mine i cannot share any code. But the line i shared is how i access the keychainstore in both classes.

**Comment by rashidasgari** [comment]
I am still having problem with this on ios9.

**Comment by melote** [comment]
Hi guys, I met this problem by using SSKeychain(another keychain wrapper). Here  it is the link [https://github.com/soffes/sskeychain/issues/75](https://github.com/soffes/sskeychain/issues/75) of related github issue.

**Comment by rashidasgari** [comment]
@melote thanks melo, this problem happen to strike me from time to time and i havnt been able to find any solution to it. Tried almost everything and im starting to think that its related to iOS9.

**Comment by melote** [comment]
Hi @rashidasgari , I was the same and I can't find any cause or solution, I met this problem on ios 8.4.x recently as well. sometimes it returned nil, otherwise it's ok most of the time.

**Comment by rashidasgari** [comment]
@melote Its getting a bit frustrating. @kishikawakatsumi did you have any luck simulating this yet?

**Comment by rashidasgari** [comment]
This seems like a bug in keychain. Another bunch of people are having the exactly same problem with another wrapper: https://github.com/nicklockwood/FXKeychain/issues/18

**Comment by rashidasgari** [comment]
@kishikawakatsumi I just found out that this behavior only happens when the device is connected to my computer and im running the app directly from xcode.

**Comment by hellChine** [comment]
I have the same problem .   I use the NSUserDefaults and UICKeyChainStore now。

**Comment by gbau** [comment]
Like @rashidasgari, I'm experiencing this problem only when running from xcode. I'm using v2.1.0. @kishikawakatsumi any luck reproducing on your end?

**Comment by iphonebytes** [comment]
@kishikawakatsumi  I am facing the same issue as describe by everyone. Earlier it was just when i connect to Xcode, now its all the time.

**Comment by zhihuitang** [comment]
ios 9.x, swift 2.0, same problem with me :(

**Comment by PrakashMaharjan** [comment]
Have anybody found solution for this issue? If yes please share here..
thanks

**Comment by sroelli** [comment]
Adding the "Share keychain entitlement" worked for me.
https://forums.developer.apple.com/message/170381#170381

**Comment by kishikawakatsumi** [comment]
Please add code signing entitlements to the app. I've just fixed at https://github.com/kishikawakatsumi/KeychainAccess/pull/221/commits/fb4529d77f4377cc24bd62f5baf15d6279f9f05f for the example project. From iOS 10, entitlements file is always needed for writing Keychain even without sharing.

<img width="1156" alt="screen shot 2016-09-14 at 22 48 41" src="https://cloud.githubusercontent.com/assets/40610/18514829/040d7066-7ace-11e6-84e2-4e373f53e60c.png">

<img width="679" alt="screen shot 2016-09-14 at 22 53 24" src="https://cloud.githubusercontent.com/assets/40610/18514845/11e36600-7ace-11e6-8a1a-e511509e43cd.png">
