### ISSUE TITLE
Requested key from UICKeyChainStore is nil in app extension 

### ISSUE THREAD

**Issue by peterwarbo** [kishikawakatsumi/UICKeyChainStore#129]
I'm using an embedded framework to share code with my main app and app extension. In the main app I use UICKeyChainStore to set a key and it successfully returns The key when requested but in my extension when I request the key it always returns nil. What could cause this behaviour?

**Comment by kishikawakatsumi** [comment]
@peterwarbo Did you set access group and turn on keychain sharing? To share keychain between multiple apps, these settings are needed.

<img width="908" alt="screen shot 2016-08-08 at 14 57 14" src="https://cloud.githubusercontent.com/assets/40610/17470596/6e2edfca-5d78-11e6-9726-3c1a3a3367dd.png">

**Comment by peterwarbo** [comment]
@kishikawakatsumi aha! Good call. I will try that and report back :)

**Comment by peterwarbo** [comment]
@kishikawakatsumi how do I invoke UICKeyChainStore with a Keychain Group?
