### ISSUE TITLE
iOS10 issues

### ISSUE THREAD

**Issue by sksyed** [kishikawakatsumi/UICKeyChainStore#134]
Are there any reported issues with new release of XCode8, iOS10 and UICKeyChainStore?

My code runs normally with XCode7.3.1 but on XCode8Beta it started breaking. UICKeychainStore doesn't seem to return anything.

I used UICKeyChainStore 1.0.5 and then 2.1.0 but it didn't help.

**Comment by ManuelOrtega** [comment]
+1

Also experiencing the same issue. Not able to retrieve anything set in UICKeychainStore in iOS 10.

Any solution?

**Comment by ManuelOrtega** [comment]
Found the solution! 

You have to enable the Keychain sharing in the capabilities section:

http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-beta-gm-in-ios-10-simulator/38543243#38543243

**Comment by HiroshiHorie** [comment]
Yes I have the same problem

**Comment by squatchus** [comment]
Do you, guys, experiencing this issue on iOS 10 in general or on some specific devices? I have the same problem only on iPad Pro simulator. My iPad Mini 2 and iPhone 5s updated to iOS 10.0.1 works just fine.

**Comment by kishikawakatsumi** [comment]
@squatchus @HiroshiHorie @ManuelOrtega @sksyed 

Please add code signing entitlements to the app. From iOS 10, entitlements file is always needed for writing Keychain even without sharing.

<img width="1156" alt="screen shot 2016-09-14 at 22 48 41" src="https://cloud.githubusercontent.com/assets/40610/18514829/040d7066-7ace-11e6-84e2-4e373f53e60c.png">

<img width="679" alt="screen shot 2016-09-14 at 22 53 24" src="https://cloud.githubusercontent.com/assets/40610/18514845/11e36600-7ace-11e6-8a1a-e511509e43cd.png">
