### ISSUE TITLE
UICKeyChainStore doesn't work in iOS 8

### ISSUE THREAD

**Issue by siancu** [kishikawakatsumi/UICKeyChainStore#14]
Just tried with Xcode 6.0 and the iOS 8 preview SDK and SecItemCopyMatching() in setData:forKey:service:accessGroup returns -34018

Can you please have a look?

Thanks!

**Comment by farhadn** [comment]
Has this been resolved? Have a user reporting issues on 8.3 and seeing this error on their device.

```<Error>:  SecOSStatusWith error:[-34018] The operation couldn’t be completed. (OSStatus error -34018 - Remote error : The operation couldn‚Äôt be completed. (OSStatus error -34018 - client has neither application-identifier nor keychain-access-groups entitlements))```

Weird thing is it doesn't always happen.
