### ISSUE TITLE
iOS10 UICKeyChainStore is null

### ISSUE THREAD

**Issue by nurmerey** [kishikawakatsumi/UICKeyChainStore#141]
Hello, just spent a whole day trying to debug why keychain was null on my app on iOS10, and realised it has a simple 2 minute fix: change the library to the new version (I got the one from Example-iOS project). I hope this saves someones time in the future.

**Comment by wjling** [comment]
I met the problem, too. I can't save data in keychain, it always return nil

**Comment by olegKa** [comment]
I found the solution here: [stackoverflow](http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-in-ios-10-simulator)

**Comment by wjling** [comment]
It just worked! Thanks! @olegKa

**Comment by kishikawakatsumi** [comment]
Closing as duplicated to https://github.com/kishikawakatsumi/UICKeyChainStore/issues/106#issuecomment-247535425
