### ISSUE TITLE
OSStatus error: [-34018] Security error has occurred.

### ISSUE THREAD

**Issue by marioacarvalho** [kishikawakatsumi/UICKeyChainStore#142]
I'm getting the title error when I try to save something into keychain. 

Any ideas?

**Comment by kishikawakatsumi** [comment]
@marioacarvalho Please add code signing entitlements to the app. From iOS 10, entitlements file is always needed for writing Keychain even without sharing.

Closing as duplicated to https://github.com/kishikawakatsumi/UICKeyChainStore/issues/106#issuecomment-247535425
