### ISSUE TITLE
Please update to swift

### ISSUE THREAD

**Issue by chinmaykdas** [kishikawakatsumi/UICKeyChainStore#149]
I need the wrapper in swift. Although I can use objective-c file in swift project, I want to make it in complete swift.

**Comment by kishikawakatsumi** [comment]
@chinmaykdas Already here: https://github.com/kishikawakatsumi/KeychainAccess
^ Does that work for you?

**Comment by chinmaykdas** [comment]
Thanks @kishikawakatsumi for your response, I will try this.
