### ISSUE TITLE
How Much Data Can be Saved into the Keychain?

### ISSUE THREAD

**Issue by victorstewart** [kishikawakatsumi/UICKeyChainStore#154]
Is there a point where you're restricted from storing anymore data into the keychain? Like 5, 20, 100MB?

Or where decrypting that amount of data during retrieval takes a noticeable about of time?

**Comment by kishikawakatsumi** [comment]
https://stackoverflow.com/questions/13488793/is-there-any-length-limit-of-string-stored-in-keychain
