### ISSUE TITLE
Feature Request: Add support for iCloud keychain?

### ISSUE THREAD

**Issue by kissfro** [kishikawakatsumi/UICKeyChainStore#16]
Sent an e-mail on this, but in retrospect probably better to post this here. 

I Believe in iOS7.01, Apple allowed us to store the keychain in iCloud if the user has it enabled. I think all you need to do is add kSecAttrSynchronizable in certain areas. Possible this could be added to this? (not comfortable with the keychain code, so don't feel comfortable making the addition as I'm not sure exactly where I should add it).

**Comment by kishikawakatsumi** [comment]
I released version 2.
It supports iCloud sharing or more features.

Example:

```
UICKeyChainStore *keychain = [UICKeyChainStore keyChainStoreWithService:@"com.example.github-token"];
keychain.synchronizable = YES;

keychain[@"kishikawakatsumi"] = @"01234567-89ab-cdef-0123-456789abcdef"
```

See also,
https://github.com/kishikawakatsumi/UICKeyChainStore#icloud_sharing
