### ISSUE TITLE
Read passwords from the macOS keychain

### ISSUE THREAD

**Issue by arturdev** [kishikawakatsumi/UICKeyChainStore#163]
Is it possible to read passwords from the keychain? 
For example, to read passwords which are saved by Safari browser for a certain website?

**Comment by kishikawakatsumi** [comment]
@arturdev Yes and no. If you have the key to uniquely identify the password, you have the chance to access the password. However, in order to read the password, user approval is required. If the user enters the administrator password at the prompt, you can retrieve the password.

**Comment by arturdev** [comment]
I'm writing a macOS application which has a login screen. On that screen, a user will type his credentials of http://example.com and if in the keychain he always has that credentials then the app should get that and prefill fields automatically. 
So using your library, how to show authentication prompt to make the user type admin's password? 
And how to get his credentials of http://example.com?

**Comment by kishikawakatsumi** [comment]
@arturdev 
<img width="646" alt="screen shot 2018-02-12 at 19 32 28" src="https://user-images.githubusercontent.com/40610/36092670-8073ad7a-102b-11e8-8129-cc03ba232f61.png">

I recommend using KeychainAccess.app as the first step. `Where` is server, `Account` is account.

**Comment by arturdev** [comment]
@kishikawakatsumi But how do that programmatically?  I'm writing a simple login form with 2 fields (email and password) and the user should enter his credentials himself. 
Long story short, I want to achieve this (see screenshot) in my macOS app: 

<img width="1737" alt="screen shot 2018-02-12 at 3 17 32 pm" src="https://user-images.githubusercontent.com/6263856/36094539-1ba57496-1008-11e8-91d2-7b0a67ff690c.png">

So, again my question is: how programmatically show authentication prompt to gain access to user's keychain in order to fetch his password of a certain website?  Does your library provide that? 
If yes, then what code to write to achieve That? 
If no, then what will you suggest to achieve that?  (Please note that my app won't be published in AppStore, so any hackish is acceptable 🙂) 

Thanks in advance!

**Comment by kishikawakatsumi** [comment]
@arturdev No you can't. You need to know the keys to access the passwords. You also need to know the keys to display such a list. Safari of cource has a list of the keys because Safari saves the passwords itself.
