### ISSUE TITLE
compile-time warnings 

### ISSUE THREAD

**Issue by mr-fixit** [kishikawakatsumi/UICKeyChainStore#166]
Under Xcode 9.4.1 and 'latest SDK' (10.3), I get ~80 compile-time warnings.

All are resolved by changing MACOSX_DEPLOYMENT_TARGET from 10.7 to 10.10.

**Comment by kishikawakatsumi** [comment]
@mr-fixit I don't think to narrow the deployment target. Please ignore those warnings. If you use CocoaPods, `inhibit_warnings` helps you like the following:

```
pod 'FUICKeyChainStore', :inhibit_warnings => true
```
