### ISSUE TITLE
Error when trying to archive using new build system in Xcode 10

### ISSUE THREAD

**Issue by AlonZilb** [kishikawakatsumi/UICKeyChainStore#169]
For what I've found it's because both versions (10.0, 11.4) share the same build settings "Product name", what can I do about it?
(Cocoapods 1.6.0.beta 2)

Thank you!

--
Multiple commands produce '/Users/doc/Library/Developer/Xcode/DerivedData/Project-dmploethkfrsshdqgntaiiyrihlf/Build/Intermediates.noindex/ArchiveIntermediates/Project/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UICKeyChainStore.framework':
1) Target 'UICKeyChainStore-iOS11.4' has create directory command with output '/Users/doc/Library/Developer/Xcode/DerivedData/Project-dmploethkfrsshdqgntaiiyrihlf/Build/Intermediates.noindex/ArchiveIntermediates/Project/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UICKeyChainStore.framework'
2) Target 'UICKeyChainStore-iOS10.0' has create directory command with output '/Users/doc/Library/Developer/Xcode/DerivedData/Project-dmploethkfrsshdqgntaiiyrihlf/Build/Intermediates.noindex/ArchiveIntermediates/Project/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/UICKeyChainStore.framework'
--

**Comment by kkishikawa-folio** [comment]
@AlonZilb Thanks for reporting. I'll investigate it.
