### ISSUE TITLE
Tryiing compile framework withing static frameworks

### ISSUE THREAD

**Issue by kleiberjp** [kishikawakatsumi/UICKeyChainStore#173]
I'm having this issue at moment compiler try build the pod `UICKeyChainStore`, ld: library not found for -lgcc_s.1, we already disable de post configuration for bitcode, and valid_archs settings. What else can I try?

**Comment by kishikawakatsumi** [comment]
I cannot reproduce this issue. Can you provide more information to reproduce or the reproducible sample project?

**Comment by kishikawakatsumi** [comment]
Closing due to no response.
