### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by Offek** [kishikawakatsumi/UICKeyChainStore#175]
Hi All,
Is it possible to get this library to work on Mac using Mac Catalyst?
`'SecAddSharedWebCredential' is unavailable` on macCatalyst.

Thanks!

**Comment by jlippold** [comment]
Just co-signing on this one. I noticed the swift version was already patched for catalyst, and im hoping for an objc update 🙏

**Comment by Heotsan** [comment]
Bumping for updates, thanks!

**Comment by Tionit** [comment]
I would've needed that too. 🙏🏼

**Comment by kishikawakatsumi** [comment]
OK
