### ISSUE TITLE
Method accepting NSError** should have a non-void return value

### ISSUE THREAD

**Issue by Simulacrotron** [kishikawakatsumi/UICKeyChainStore#32]
The following methods all return analysis warnings 'Method accepting NSError** should have a non-void return value to indicate whether an error occurred'
```
- (void)setString:(NSString *)string forKey:(NSString *)key error:(NSError *__autoreleasing *)error;
- (void)setData:(NSData *)data forKey:(NSString *)key error:(NSError *__autoreleasing *)error;
- (void)removeItemForKey:(NSString *)key error:(NSError *__autoreleasing *)error;
- (void)removeAllItemsWithError:(NSError *__autoreleasing *)error;
- (void)synchronizeWithError:(NSError *__autoreleasing *)error;
```

**Comment by pablokabbee** [comment]
Can you create the cocoa pods with this fix? Thanks

**Comment by kishikawakatsumi** [comment]
Released v1.1.1
https://raw.githubusercontent.com/CocoaPods/Specs/036016b9ca0850c8c2e751191515dc562be8c8f3/Specs/UICKeyChainStore/1.1.1/UICKeyChainStore.podspec.json

Thank you for waiting.

**Comment by Simulacrotron** [comment]
Thank you!

**Comment by pabloroca** [comment]
Thanks!

**Comment by AlexGingell** [comment]
This is old, but as I just had to fix this myself, I thought I would mention it.
Should you not be calling:

`return *error == nil;`

instead of

`return error == nil;`
