### ISSUE TITLE
NSUbiquitousKeyValueStore error:  no valid com.apple.developer.ubiquity-kvstore-identifier entitlement

### ISSUE THREAD

**Issue by nashfive** [kishikawakatsumi/UICKeyChainStore#62]
Hi,

At startup, I have this "error": 
```Objective-C
NSUbiquitousKeyValueStore error:  no valid com.apple.developer.ubiquity-kvstore-identifier entitlement
```
I don't wanna enable the iCloud entitlement because it's an In-House distributed one, and also for privacy reason, required by my client ;-)
I would like to know if I can safely ignore that error... Or is there a way to disable the iCloud Keychain feature in UICKeyChainStore ?

Note: I am using your project because it is a [FCUUID](https://github.com/fabiocaccamo/FCUUID)'s dependency.

**Comment by kishikawakatsumi** [comment]
It seems that UICKeyChainStore had nothing to do with it.
The FCUUID enabled iCloud sharing by default.

https://github.com/fabiocaccamo/FCUUID/blob/master/FCUUID/FCUUID.m#L43
https://github.com/fabiocaccamo/FCUUID/blob/master/FCUUID/FCUUID.m#L218

Probably FCUUID print the error message.
I think that you have reported in [the issue of FCUUID](https://github.com/fabiocaccamo/FCUUID/issues) has obtained good results.

**Comment by fabiocaccamo** [comment]
@nashfive Have you solved this issue? I think that you just need to disable the Key Value Store option in the iCloud entitlements. 

If you don't solve it, please report the issue to FCUUID.

**Comment by nashfive** [comment]
Hey guys, sorry for the late update, I was busy. 
So yes I didn't activate the iCloud capability and it's working as expecting. I haven't search for a way to disable the error message at runtime yet. It's less annoying than a warning but if I find a way I'll make a pull request. 

Thanks for your feedback.
