### ISSUE TITLE
TouchID dialog everytime

### ISSUE THREAD

**Issue by adamrushy** [kishikawakatsumi/UICKeyChainStore#65]
Not sure if it's an issue or not, but I am getting the dialog for Touch ID on every save. Which is reasonable but I am saving more than one object in a single call which again requests the dialog twice.

Can it not display just the once per call?

**Comment by adamrushy** [comment]
This works deleting the key prior to saving, how about retrieving I still get the dialog twice when retrieving:

        UICKeyChainStore *keychain = [UICKeyChainStore keyChainStoreWithService:@"userLoginDetails"];
        
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
            [keychain setAccessibility:UICKeyChainStoreAccessibilityWhenPasscodeSetThisDeviceOnly
                  authenticationPolicy:UICKeyChainStoreAuthenticationPolicyUserPresence];
            keychain.authenticationPrompt = @"Authenticate to update your access token";
            
            self.loginViewModel.username = keychain[@"username"];
            self.loginViewModel.password = keychain[@"password"];
            
            [self login];
        });

**Comment by kishikawakatsumi** [comment]
There is no way to stop the dialog is shown each time to retrieve the values. It's iOS specification.
In general, should not protect the username, just store in the keychian. Protect with Touch ID only the password.

**Comment by adamrushy** [comment]
Okay makes sense.

Thanks for your help!
