### ISSUE TITLE
Accessing "Cancel" on touch ID request

### ISSUE THREAD

**Issue by adamrushy** [kishikawakatsumi/UICKeyChainStore#66]
When I display the Touch ID prompt if the user taps cancel, it continues running the code. Is their any blocks or delegates to check when a user taps cancel?

```objective-c
        // Post the Touch ID dialog
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
            [keychain setAccessibility:UICKeyChainStoreAccessibilityWhenPasscodeSetThisDeviceOnly
                  authenticationPolicy:UICKeyChainStoreAuthenticationPolicyUserPresence];
            keychain.authenticationPrompt = [NSString stringWithFormat:@"%@ %@ %@", user.title, user.firstName, user.lastName];
            
            [self login];
        });
```

**Comment by kishikawakatsumi** [comment]
You seem to have a little misunderstood.
`keychain.authenticationPrompt = ...` just sets custom message for Touch ID dialog. Display of the dialog will occur by the querying or updating the value.

If the value is Touch ID protected, the dialog is shown when querying the value. While the dialog is displayed, the execution of the method will be blocked. (Therefore, need to run in the background thread.)

So there is no call back, delegate methods, and so on. That the following line is executed is either or authentication has been canceled or was successful.

```objective-c
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_BACKGROUND, 0), ^{
    NSError *error = nil;
    NSString *password = [keychain stringForKey:@"kishikawakatsumi"
                                          error:&error]; // Blocked during prompt displayed

    // Only when it is canceled either authentication is successful to reach here
    if (error) {
        // If the user cancelled authentication, the error code is -25293 (errSecAuthFailed)
    } else {
        // Authentication succeeded
    }
});
```
