### ISSUE TITLE
2.0.0 no longer compatible with ios < 7

### ISSUE THREAD

**Issue by thenewrohirrim** [kishikawakatsumi/UICKeyChainStore#69]
Even though webpage and cocoapods claim compatibility with ios 4.3 and later, the use of kSecAttrSynchronizable in UIKeychainStore.m means that it's only compatible with ios 7 and later, as that constant is not available before.

Great project though - thank you!

**Comment by hungtruong** [comment]
+1

**Comment by emartynov** [comment]
Discover same here

**Comment by kishikawakatsumi** [comment]
Fixed https://github.com/kishikawakatsumi/UICKeyChainStore/issues/69

A lot of thanks for @emartynov

**Comment by kishikawakatsumi** [comment]
Released 2.0.3, includes this fix https://raw.githubusercontent.com/CocoaPods/Specs/b07d8f49c989bc973861e5f9b28078c164e152c7/Specs/UICKeyChainStore/2.0.3/UICKeyChainStore.podspec.json

**Comment by thenewrohirrim** [comment]
works a treat, thank you

**Comment by emartynov** [comment]
It was pleasure! You can close the ticket now
