### ISSUE TITLE
remove keyChainStoreWithServer

### ISSUE THREAD

**Issue by marinotws** [kishikawakatsumi/UICKeyChainStore#79]
Hi, i have used this function : 

keychain = [UICKeyChainStore keyChainStoreWithServer:[NSURL URLWithString:myUrl] protocolType:UICKeyChainStoreProtocolTypeHTTPS];
keychain[user] = password;

how to remove next a user with his password ?
and how to remove all keyChainStoreWithServer ?

thanks

**Comment by kishikawakatsumi** [comment]
Like below:

```obj
[keychain removeItemForKey:user];
```

or


```objc
keychain[user] = nil;
```

Hope this answers your question.

**Comment by marinotws** [comment]
thanks a lot.
