### ISSUE TITLE
dyld: Symbol not found: _kSecAttrAccessControl

### ISSUE THREAD

**Issue by danielkbx** [kishikawakatsumi/UICKeyChainStore#80]
kSecAttrAccessControl has been introduced in iOS8 but is used without any availability checks inUICKeyChainStore.m:1183.

This causes any pre iOS8 app to crash due to an unknown symbol.

**Comment by kishikawakatsumi** [comment]
It seems accessing `kSecAttrAccessControl` contant is guarded by Foundation Version checking.

Like below:
https://github.com/kishikawakatsumi/UICKeyChainStore/blob/master/Lib/UICKeyChainStore/UICKeyChainStore.m#L1164

Could you please show reproduce sample code?

**Comment by danielkbx** [comment]
You're right, it is guarded correctly. The target needs to link the Security framework weakly. Probably you should add this to the Readme.md (set the dropdown to "optional" instead of "required").

Doing so will make the app run on iOS versions where the constants do not yet exist.
