### ISSUE TITLE
2.0.4 compatibility issue with iOS7

### ISSUE THREAD

**Issue by WhiteHexagon** [kishikawakatsumi/UICKeyChainStore#84]
I'm starting out with AWS and following their getting started guide. The 'AWSCore' pod pulls in UICKeyChainStore pod with a 2.0.0 dependency, but I'm seeing some compile time issues in the .h and .m, for example:

__OSX_AVAILABLE_STARTING(__MAC_10_9, __IPHONE_4_0);

typedef NS_ENUM(NSInteger, UICKeyChainStoreAuthenticationPolicy) {
    UICKeyChainStoreAuthenticationPolicyUserPresence = kSecAccessControlUserPresence,
};
gives a 'use of undeclared identifier kSecAccessControlUserPresence'

I'm also seeing many lines with:

__OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);

and from what I can tell the error is something to do with 8_0 because changing that to 7_0 seems to 'hide' the problem. 

I'm using XCode 5.1.1 (base SDK 7.1)  and OSX 10.8.5

**Comment by kishikawakatsumi** [comment]
Yes, Xcode 5.x does not know iOS 8 and OS X 10.0. Can you upgrade Xcode version to 6.x? If you cannot, let me know the reason since harder to adopt the old development environment than adopt to the old runtime environment. If there is no special reason, I really want you to use in the newer development environment.

**Comment by WhiteHexagon** [comment]
Thanks for the quick response, and I do appreciate the preference to move forwards.  I'm trying to do the same :) but sadly I cant upgrade to XCode 6 yet, since I'm on 10.8.5 and its not supported, and I cant update to 10.9 since Apple removed it.  Hopefully we can jump to 10.10 in the next couple of months though! 

Interestingly the AWS tutorial lists XCode 5 and iOS 7 as minimum requirements:

http://docs.aws.amazon.com/mobile/sdkforios/developerguide/setup.html#include-the-sdk-for-ios-in-an-existing-application

I dont know if that makes a difference, since you might get further requests for this, unless they also increase their entry level requirements.  Thanks and feel free to close this item now you have confirmed the reason.

**Comment by WhiteHexagon** [comment]
PS If I raise an issue against AWS what pod version should they be pointing to for XCode5 and iOS7 compatibility please?

**Comment by jeremiahbunton** [comment]
I was having the same issue but upgrading to Xcode 6 resolved the issues that I was having with undeclared variables and such.

Thank you.
