### ISSUE TITLE
keychain access during lock screen

### ISSUE THREAD

**Issue by mmarszal** [kishikawakatsumi/UICKeyChainStore#9]
Hi There,

I've been using UICkeyChainStore for quite a while now, and find it really great.
However, I added a new feature to my app that allows connecting to devices in the background. When i try to access a password when the device is locked, UICKeyChainStore cannot retrieve the password due to some security settings.

I did some searching, and i found that i need to set the key kSecAttrAccessible to have value kSecAttrAccessibleAlways. However I'm not sure where to stick this in your library.

I tried putting it in the setData method with the other queries:
[query setObject:(__bridge id)kSecAttrAccessibleAlways forKey:(__bridge id)kSecAttrAccessible];

But I still couldn't get it to work. 

Could you advise me how to properly set this attribute?

Thank you,

-Mark

**Comment by kishikawakatsumi** [comment]
I released version 2.
It supports accessibility or more attributes.


For example:

```
UICKeyChainStore *keychain = [UICKeyChainStore keyChainStoreWithService:@"com.example.github-token"];
keychain.accessibility = UICKeyChainStoreAccessibilityAfterFirstUnlock;

keychain[@"kishikawakatsumi"] = @"01234567-89ab-cdef-0123-456789abcdef"
```

See also,
https://github.com/kishikawakatsumi/UICKeyChainStore#accessibility
