### ISSUE TITLE
sometime return nil

### ISSUE THREAD

**Issue by songbaoqiang** [kishikawakatsumi/UICKeyChainStore#91]
UICKeyChainStore *keychain = [UICKeyChainStore keyChainStoreWithService:KKEYCHAINServiceName];
    NSString *currentPassport = [keychain stringForKey:KOPENUDIDKEY];

sometime return nil  and sometime return right value.

**Comment by ivanstojkovicapps** [comment]
it always return nil for me with exact same code

**Comment by rashidasgari** [comment]
I have the exactly same problem. sometimes it returns nil!

**Comment by kishikawakatsumi** [comment]
Duplicate https://github.com/kishikawakatsumi/UICKeyChainStore/issues/106
