### ISSUE TITLE
Release notes on v2.0.3, v2.0.4 and v2.0.5

### ISSUE THREAD

**Issue by briankracoff** [kishikawakatsumi/UICKeyChainStore#94]
I'm not sure what's changed so I haven't updated from v2.0.2.

**Comment by kishikawakatsumi** [comment]
I agree with you. But I have not enough time now. I'm going to do about that a few days later. Thanks.

**Comment by kishikawakatsumi** [comment]
@briankracoff Done! Thak you notice it.
